### ISSUE TITLE
Incomplete Compliance with MIT License for larabug/larabug

### ISSUE THREAD

**Issue by Cannonb4ll** [sleuren/laravel#2]
I am the maintainer of the https://github.com/larabug/larabug repository, which is an open-source package released under the MIT License. It has come to my attention that your repository includes a significant portion of the code from https://github.com/larabug/larabug, but does not properly attribute the source or include the original MIT License and copyright notice.

Additionally, we've noticed that several other repositories from "sleuren" appears to contain code from other open-source projects that are also licensed under the MIT License. We strongly recommend that you review these as well to ensure you are in full compliance with their respective licenses. (Example: https://github.com/facade/flare-client-js vs https://github.com/sleuren/sleuren-js)

The MIT License requires that the copyright notice and the license text be included in any substantial copies or substantial portions of the Software. This is essential for maintaining the open-source nature of the project and crediting the contributors for their work.

In order to comply with the MIT License, please take the following actions:

* Add the original copyright notice found in https://github.com/larabug/larabug to the relevant files in your repository.
* Include a copy of the original MIT License from https://github.com/larabug/larabug in your repository.
* Failure to comply with the terms of the MIT License could put you in a legal situation and undermine the principles of open-source software.

Please confirm the completion of these steps by replying to this issue. Thank you for your prompt attention to this matter, and for your respect for the terms of open-source licenses.

**Comment by vanling** [comment]
@fr3on is this fixed?

**Comment by fr3on** [comment]
Project will closed

**Comment by vanling** [comment]
When? @fr3on
